return {
  "rafamadriz/friendly-snippets",
  "neoclide/vim-jsx-improve",
  "neovim/nvim-lspconfig",
  "folke/lsp-colors.nvim",
  "folke/which-key.nvim",
  "gko/vim-coloresque",
  "honza/vim-snippets",
  { "autozimu/LanguageClient-neovim", build = "bash install.sh" },
  "hrsh7th/vim-vsnip-integ",
  "nvim-tree/nvim-web-devicons",
  "mattn/emmet-vim",
  "mfussenegger/nvim-jdtls",
  "mhartington/formatter.nvim",
  "nanotee/sqls.nvim",
  "norcalli/nvim-colorizer.lua",
  "nvim-lua/lsp-status.nvim",
  "nvim-lua/plenary.nvim",
  "nvim-lua/popup.nvim",
  "kdheepak/lazygit.nvim",
  "nvim-treesitter/playground",
  "tpope/vim-surround",
  "onsails/lspkind-nvim",
  "navarasu/onedark.nvim",
  "udalov/kotlin-vim",
  { "romgrk/barbar.nvim", dependencies = "nvim-web-devicons" },
  "simrat39/rust-tools.nvim",
  { "akinsho/flutter-tools.nvim", dependencies = "nvim-lua/plenary.nvim" },
  "simrat39/symbols-outline.nvim",
  { "ray-x/guihua.lua", build = "cd lua/fzy && make" },
  "ray-x/lsp_signature.nvim",
  "voldikss/vim-floaterm",
  "hrsh7th/nvim-cmp",
  "hrsh7th/cmp-path",
  "hrsh7th/cmp-buffer",
  "hrsh7th/cmp-cmdline",
  "hrsh7th/cmp-nvim-lsp",
  "hrsh7th/cmp-nvim-lua",
  "hrsh7th/cmp-emoji",
  "hrsh7th/cmp-calc",
  "hrsh7th/cmp-omni",
  "L3MON4D3/LuaSnip",
}
